language: generic

services: 
  - docker

before_install:
  - docker build -t hemanditwiz/react-redux-ts-docker-boilerplate -f Dockerfile.dev .  

script:
  - docker run -e CI=true hemanditwiz/react-redux-ts-docker-boilerplate npm run test  